#!/usr/bin/env python

from ete3 import Tree, TreeStyle
import argparse
import os

def main(arguments):
        t = Tree(arguments.newick)
        ts = TreeStyle()
        ts.show_leaf_name = True
        ts.show_branch_length = True
        ts.show_branch_support = True
        basename = os.path.basename(arguments.newick)
        t.render(basename + '.png', w=200, units="mm", tree_style=ts)

if __name__ == "__main__":
        parser = argparse.ArgumentParser()
        parser.add_argument('newick', action="store")
        arguments = parser.parse_args()
        main(arguments)
